project:
  type: website

website:
  title: "ISSS626-wp"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise3"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "Hands-on Exercise4"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
      - text: "Hands-on Exercise5"
        href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
      - text: "Hands-on Exercise5.1"
        href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.1.html"
      - text: "Hands-on Exercise6"
        href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "Hands-on Exercise7"
        href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - text: "Hands-on Exercise8"
        href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
    - text: "In-class Exercise"
      menu:
      - text: "In-class_Learning_week3"
        href: "In-class_Ex/In-class_Learning_week3.html"
      - text: "In-class_Learning_week4"
        href: "In-class_Ex/In-class_Learning_week4.html"
      - text: "In-class_Learning_week4_solution"
        href: "In-class_Ex/In-class_Learning_week4_solution.html"
      - text: "In-class_Learning_week5"
        href: "In-class_Ex/In-class_Learning_week5.html"
      - text: "In-class_Learning_week6"
        href: "In-class_Ex/In-class_Learning_week6.html"
      - text: "In-class_Learning_week5_solution"
        href: "In-class_Ex/In-class_Learning_week5_solution.html"
      - text: "In-class_Learning_week7"
        href: "In-class_Ex/In-class_Learning_week7.html"
      - text: "In-class_Learning_week8"
        href: "In-class_Ex/In-class_Learning_week8.html"
      - text: "In-class Exercise03a"
        href: "In-Class_Ex/In-class_Ex03a.html"
    - text: "Take-home exercise"
      menu:
      - text: "Take-Home Exercise1a_Restaurant"
        href: "Assignment1/Take-Home_Exercise_1a.html"
      - text: "Take-Home Exercise1b_Food Kiosks"
        href: "Assignment1/Take-Home_Exercise_1b.html"
      - text: "Take-Home Exercise1c_Real estate developers"
        href: "Assignment1/Take-Home_Exercise_1c.html"
      - text: "Take-Home2"
        href: "Assignment_2/Take-Home_Exercise_2.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

