{
  "hash": "ad90551bb99ee3f656a18734f5d15517",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment_3\"\nauthor: \"HTC\"\ndate: \"October 30, 2025\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc-depth: 4\n    toc-expand: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Overview\n\n## Import Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(httr, tidyverse,sf,tmap,jsonlite, progress, spdep,GWmodel, SpatialML,rsample, Metrics, knitr, kableExtra, spatialRF, randomForestExplainer,ggpubr,corrplot,sfdep,gtsummary,performance,RColorBrewer)\n```\n:::\n\n\n## Import and Filter Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex/In-class_Learning_week8\")\nHDBresale <- read_csv(\"data/HDBresale.csv\") %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2025-09\" & month < \"2025-10\")\n```\n:::\n\n\n## Aspatial Data Wrangling and Integrating Geometry Retrieval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$street_name <-gsub(\n  \"ST\\\\.\", \"SAINT\",\n  HDBresale$street_name\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(HDBresale)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address,\n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\",\n                \"pageNum\" = \"1\")\n  res <- GET(base_url, query = query)\n  restext <- content(res, as= \"text\")\n  \n  output <- fromJSON(restext) %>%\n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n  \n  return(output)\n}\n```\n:::\n\n\nNext, the code chunk below will be used to to execute the geocoding function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex/In-class_Learning_week8\")\nwrite_rds(HDBresale, \"data/model/HDBresale.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex/In-class_Learning_week8\")\nHDBresale <- read_rds(\"data/model/HDBresale.rds\")\n```\n:::\n\n\n### **Converting to an sf object**\n\nBefore performing proximity analysis, it is important to ensure that:\n\n-   both input data sets must be in sf objects, and\n\n-   they must be in similar projected coordinates systems.\\\n\nIn the code chunk below,\n\n-   `st_as_sf()` is used to convert HDBresale tibble data.frame to sf object by using values from LONGITUDE and LATITUDE columns to form the geometry features.\n\n-   `st_transform()` is then used to transform the sf object into svy21 projected coordinates system.\n\n-   the output sf object is called *HDBresale_sf*. It is in **sf data.frame** format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\",\"LATITUDE\"),\n    crs = 4326) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n## Geospatial and Asptial Data Wrangling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex/In-class_Learning_week8\")\npreschool = st_read(\"data/PreSchoolsLocation.kml\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `C:\\Users\\HT Chen\\Desktop\\ISSS626\\ISSS626-wp\\In-Class_Ex\\In-class_Learning_week8\\data\\PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### **Counting number of preschools**\n\nLastly, code chunk below will be used to count the number of pre-schools located within 350m of each HDB property.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(\n  HDBresale_sf, preschool, dist= 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(prischool_350m = map_int(within_350m, length))\n```\n:::\n\n\n### **Computing shortest distance**\n\nInstead of counting number of preschools located within 350m of each HDB resale property, code chunk below is used to compute the distance between the nearest preschool from each HDB resale property.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    PROX_PRESCHOOL = as.numeric(\n      st_distance(geometry,\n                  preschool[st_nearest_feature(\n                    geometry, preschool), ], \n                  by_element = TRUE)\n      )\n    )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex08\")\nmdata <- read_rds(\"data/rawdata/mdata.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nHDB_sample <- mdata %>%\n  sample_n(1500)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nOverlapping_points <- HDB_sample %>%\n  mutate(overlap = length(st_equals(., .))>1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample <- HDB_sample %>%\n  st_jitter(amount = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_CBD\"                 \"PROX_ELDERLYCARE\"        \n [7] \"PROX_HAWKER\"              \"PROX_MRT\"                \n [9] \"PROX_PARK\"                \"PROX_GOOD_PRISCH\"        \n[11] \"PROX_MALL\"                \"PROX_CHAS\"               \n[13] \"PROX_SUPERMARKET\"         \"WITHIN_350M_KINDERGARTEN\"\n[15] \"WITHIN_350M_CHILDCARE\"    \"WITHIN_350M_BUS\"         \n[17] \"WITHIN_1KM_PRISCH\"        \"geometry\"                \n```\n\n\n:::\n:::\n\n\n## Exploratory Data Analysis (EDA)\n\n### **EDA using statistical graphics**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDB_sample, \n       aes(x=`resale_price`)) +\n  geom_histogram(bins=30, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe histogram shows that:\n\nMost resale prices cluster between \\$280,000 and \\$500,000.\n\nThe distribution has a long right tail, meaning a smaller number of flats have very high prices (e.g., \\> \\$700,000).\n\nThis means the majority of HDB flats are moderately priced, but a few high-value flats (executive units, larger flats, central locations) pull the tail to the right.\n\nStatistically, the skewed dsitribution can be normalised by using log transformation. The code chunk below is used to derive a new variable called LOG_resale_price by using a log transformation on the variable resale_price. It is performed using `mutate()` of **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample <- HDB_sample %>%\n  mutate(`LOG_resale_price` = log(resale_price))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDB_sample, \n       aes(x=`LOG_resale_price`)) +\n  geom_histogram(bins=30, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_CBD\"                 \"PROX_ELDERLYCARE\"        \n [7] \"PROX_HAWKER\"              \"PROX_MRT\"                \n [9] \"PROX_PARK\"                \"PROX_GOOD_PRISCH\"        \n[11] \"PROX_MALL\"                \"PROX_CHAS\"               \n[13] \"PROX_SUPERMARKET\"         \"WITHIN_350M_KINDERGARTEN\"\n[15] \"WITHIN_350M_CHILDCARE\"    \"WITHIN_350M_BUS\"         \n[17] \"WITHIN_1KM_PRISCH\"        \"geometry\"                \n[19] \"LOG_resale_price\"        \n```\n\n\n:::\n:::\n\n\n### **Multiple Histogram Plots distribution of variables**\n\nSmall multiple histograms (also known as trellis plot) by using `ggarrange()` of [**ggpubr**](https://cran.r-project.org/web/packages/ggpubr/index.html) package.\n\nThe code chunk below is used to create 12 histograms. Then, `ggarrange()` is used to organised these histogram into a 3 columns by 4 rows small multiple plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfloor_area_sqm <- ggplot(data=HDB_sample, \n                   aes(x= `floor_area_sqm`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nremaining_lease_mths <- ggplot(data=HDB_sample, \n              aes(x= `remaining_lease_mths`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_HAWKER <- ggplot(data=HDB_sample, \n                   aes(x= `PROX_HAWKER`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_MRT <- ggplot(data=HDB_sample, \n                         aes(x= `PROX_MRT`)) + \n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_ELDERLYCARE <- ggplot(data=HDB_sample, \n                           aes(x= `PROX_ELDERLYCARE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nWITHIN_350M_CHILDCARE <- ggplot(data=HDB_sample, \n                               aes(x= `WITHIN_350M_CHILDCARE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_SUPERMARKET <- ggplot(data=HDB_sample, \n                             aes(x= `PROX_SUPERMARKET`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_GOOD_PRISCH <- ggplot(data=HDB_sample, \n                            aes(x= `PROX_GOOD_PRISCH`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_MALL <- ggplot(data=HDB_sample, \n                   aes(x= `PROX_MALL`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_PARK <- ggplot(data=HDB_sample, \n                    aes(x= `PROX_PARK`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nWITHIN_350M_KINDERGARTEN <- ggplot(data=HDB_sample, \n                           aes(x= `WITHIN_350M_KINDERGARTEN`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_CBD <- ggplot(data=HDB_sample, \n                               aes(x= `PROX_CBD`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nggarrange(floor_area_sqm, remaining_lease_mths, PROX_HAWKER, PROX_MRT, \n          PROX_ELDERLYCARE, WITHIN_350M_CHILDCARE,\n          PROX_SUPERMARKET, PROX_GOOD_PRISCH, PROX_MALL,\n          PROX_PARK, WITHIN_350M_KINDERGARTEN, PROX_CBD,  \n          ncol = 3, nrow = 4)\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n### **Drawing Statistical Point Map**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex07\")\nmpsz = st_read(dsn = \"data/geospatial\", \n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\Users\\HT Chen\\Desktop\\ISSS626\\ISSS626-wp\\Hands-on_Ex\\Hands-on_Ex07\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n### Point Symbol Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21)+\n  tm_polygons() +\ntm_shape(HDB_sample) +  \n  tm_dots(fill = \"resale_price\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style=\"quantile\")) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## **Hedonic Pricing Modelling in R**\n\n### **Simple Linear Regression Method(Conventional OLS Not Recommended) for Demonstration**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_slr <- lm(formula=resale_price ~ floor_area_sqm, \n                data = HDB_sample)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDB_sample_slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm, data = HDB_sample)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-216070  -75935  -28011   29476  680233 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    530879.5    41160.1  12.898   <2e-16 ***\nfloor_area_sqm  -1075.7      431.3  -2.494   0.0127 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 118200 on 1498 degrees of freedom\nMultiple R-squared:  0.004136,\tAdjusted R-squared:  0.003471 \nF-statistic: 6.221 on 1 and 1498 DF,  p-value: 0.01273\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDB_sample,  \n       aes(x=`floor_area_sqm`, y=`resale_price`)) +\n  geom_point() +\n  geom_smooth(method = lm)\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## **Multiple Linear Regression Method**\n\n### Multicollinearity Check\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_CBD\"                 \"PROX_ELDERLYCARE\"        \n [7] \"PROX_HAWKER\"              \"PROX_MRT\"                \n [9] \"PROX_PARK\"                \"PROX_GOOD_PRISCH\"        \n[11] \"PROX_MALL\"                \"PROX_CHAS\"               \n[13] \"PROX_SUPERMARKET\"         \"WITHIN_350M_KINDERGARTEN\"\n[15] \"WITHIN_350M_CHILDCARE\"    \"WITHIN_350M_BUS\"         \n[17] \"WITHIN_1KM_PRISCH\"        \"geometry\"                \n[19] \"LOG_resale_price\"        \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsf [1,500 × 19] (S3: sf/tbl_df/tbl/data.frame)\n $ resale_price            : num [1:1500] 405000 500888 385000 485000 418000 ...\n $ floor_area_sqm          : num [1:1500] 109 87 103 93 93 84 93 103 103 105 ...\n $ storey_order            : int [1:1500] 1 2 2 2 5 1 3 2 2 3 ...\n $ remaining_lease_mths    : num [1:1500] 787 662 821 1147 1134 ...\n $ PROX_CBD                : num [1:1500] 11.73 6.56 14.32 13.93 18.19 ...\n $ PROX_ELDERLYCARE        : num [1:1500] 0.429 0.611 0.761 0.234 2.499 ...\n $ PROX_HAWKER             : num [1:1500] 0.481 0.283 0.859 0.97 0.601 ...\n $ PROX_MRT                : num [1:1500] 0.742 1.944 0.939 0.101 0.86 ...\n $ PROX_PARK               : num [1:1500] 1.262 0.212 0.646 1.102 0.21 ...\n $ PROX_GOOD_PRISCH        : num [1:1500] 0.285 0.395 2.677 4.337 8.567 ...\n $ PROX_MALL               : num [1:1500] 0.519 0.446 0.862 0.634 0.849 ...\n $ PROX_CHAS               : num [1:1500] 0.0761 0.1932 0.4805 0.0457 0.1108 ...\n $ PROX_SUPERMARKET        : num [1:1500] 0.3011 0.2594 0.5729 0.0457 0.5656 ...\n $ WITHIN_350M_KINDERGARTEN: int [1:1500] 1 2 0 0 0 0 1 1 1 1 ...\n $ WITHIN_350M_CHILDCARE   : int [1:1500] 3 3 4 4 2 6 3 5 3 2 ...\n $ WITHIN_350M_BUS         : int [1:1500] 11 3 4 11 6 11 7 8 4 7 ...\n $ WITHIN_1KM_PRISCH       : int [1:1500] 4 3 3 4 2 5 5 2 3 2 ...\n $ geometry                :sfc_POINT of length 1500; first list element:  'XY' num [1:2] 39422 37094\n $ LOG_resale_price        : num [1:1500] 12.9 13.1 12.9 13.1 12.9 ...\n - attr(*, \"sf_column\")= chr \"geometry\"\n - attr(*, \"agr\")= Factor w/ 3 levels \"constant\",\"aggregate\",..: NA NA NA NA NA NA NA NA NA NA ...\n  ..- attr(*, \"names\")= chr [1:18] \"resale_price\" \"floor_area_sqm\" \"storey_order\" \"remaining_lease_mths\" ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 18 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 27363.82 ymin: 31715.43 xmax: 41466.83 ymax: 48032.52\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 19\n  resale_price floor_area_sqm storey_order remaining_lease_mths PROX_CBD\n         <dbl>          <dbl>        <int>                <dbl>    <dbl>\n1       405000            109            1                  787    11.7 \n2       500888             87            2                  662     6.56\n3       385000            103            2                  821    14.3 \n4       485000             93            2                 1147    13.9 \n5       418000             93            5                 1134    18.2 \n6       288000             84            1                  770    16.3 \n# ℹ 14 more variables: PROX_ELDERLYCARE <dbl>, PROX_HAWKER <dbl>,\n#   PROX_MRT <dbl>, PROX_PARK <dbl>, PROX_GOOD_PRISCH <dbl>, PROX_MALL <dbl>,\n#   PROX_CHAS <dbl>, PROX_SUPERMARKET <dbl>, WITHIN_350M_KINDERGARTEN <int>,\n#   WITHIN_350M_CHILDCARE <int>, WITHIN_350M_BUS <int>,\n#   WITHIN_1KM_PRISCH <int>, geometry <POINT [m]>, LOG_resale_price <dbl>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_num <- HDB_sample %>% \n  st_drop_geometry() %>%\n  select(where(is.numeric))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(HDB_sample_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [1,500 × 18] (S3: tbl_df/tbl/data.frame)\n $ resale_price            : num [1:1500] 405000 500888 385000 485000 418000 ...\n $ floor_area_sqm          : num [1:1500] 109 87 103 93 93 84 93 103 103 105 ...\n $ storey_order            : int [1:1500] 1 2 2 2 5 1 3 2 2 3 ...\n $ remaining_lease_mths    : num [1:1500] 787 662 821 1147 1134 ...\n $ PROX_CBD                : num [1:1500] 11.73 6.56 14.32 13.93 18.19 ...\n $ PROX_ELDERLYCARE        : num [1:1500] 0.429 0.611 0.761 0.234 2.499 ...\n $ PROX_HAWKER             : num [1:1500] 0.481 0.283 0.859 0.97 0.601 ...\n $ PROX_MRT                : num [1:1500] 0.742 1.944 0.939 0.101 0.86 ...\n $ PROX_PARK               : num [1:1500] 1.262 0.212 0.646 1.102 0.21 ...\n $ PROX_GOOD_PRISCH        : num [1:1500] 0.285 0.395 2.677 4.337 8.567 ...\n $ PROX_MALL               : num [1:1500] 0.519 0.446 0.862 0.634 0.849 ...\n $ PROX_CHAS               : num [1:1500] 0.0761 0.1932 0.4805 0.0457 0.1108 ...\n $ PROX_SUPERMARKET        : num [1:1500] 0.3011 0.2594 0.5729 0.0457 0.5656 ...\n $ WITHIN_350M_KINDERGARTEN: int [1:1500] 1 2 0 0 0 0 1 1 1 1 ...\n $ WITHIN_350M_CHILDCARE   : int [1:1500] 3 3 4 4 2 6 3 5 3 2 ...\n $ WITHIN_350M_BUS         : int [1:1500] 11 3 4 11 6 11 7 8 4 7 ...\n $ WITHIN_1KM_PRISCH       : int [1:1500] 4 3 3 4 2 5 5 2 3 2 ...\n $ LOG_resale_price        : num [1:1500] 12.9 13.1 12.9 13.1 12.9 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot(cor(HDB_sample_num[, 1:18]), \n         diag = FALSE, \n         order = \"AOE\",\n         tl.pos = \"td\", \n         tl.cex = 0.6, \n         number.cex = 0.4,\n         method = \"number\", \n         type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n**1. Very Strong Correlations**\n\n**🔵 LOG_resale_price vs resale_price (\\~0.98)**\n\nExpected, because log price is a transformation of the actual resale price.\n\nThey should not be used together in regression (perfect multicollinearity).\n\n**2. Moderate Positive Relationships**\n\n**🔵 Prox_CBD vs Prox_GOOD_PRISCH(\\~0.65)**\n\nHDB flats closer to the CBD also tend to be closer to good primary schools.\n\nThis reflects location-based clustering:\n\nThe central region has both higher prestige schools and shorter distances to the CBD.\n\n**🔵 Prox_CBD vs resale_price (\\~0.62)**\n\nThe farther a flat is from the CBD, the lower its resale price tends to be\n\n### **Filter the Multicollinearity Factor**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample <- HDB_sample %>% select(-PROX_CBD)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_ELDERLYCARE\"         \"PROX_HAWKER\"             \n [7] \"PROX_MRT\"                 \"PROX_PARK\"               \n [9] \"PROX_GOOD_PRISCH\"         \"PROX_MALL\"               \n[11] \"PROX_CHAS\"                \"PROX_SUPERMARKET\"        \n[13] \"WITHIN_350M_KINDERGARTEN\" \"WITHIN_350M_CHILDCARE\"   \n[15] \"WITHIN_350M_BUS\"          \"WITHIN_1KM_PRISCH\"       \n[17] \"geometry\"                 \"LOG_resale_price\"        \n```\n\n\n:::\n:::\n\n\n### **Building a hedonic pricing model using multiple linear regression method**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_mlr <- lm(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK  +\n    PROX_GOOD_PRISCH + PROX_MALL +\n    PROX_CHAS  + PROX_SUPERMARKET + \n    WITHIN_350M_KINDERGARTEN   + WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample)\nsummary(HDB_sample_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + storey_order + remaining_lease_mths + \n    PROX_ELDERLYCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + PROX_GOOD_PRISCH + \n    PROX_MALL + PROX_CHAS + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n    data = HDB_sample)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-213969  -43835   -5738   36034  346900 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              174861.10   34344.17   5.091 4.01e-07 ***\nfloor_area_sqm             1955.08     293.17   6.669 3.63e-11 ***\nstorey_order              17533.19    1063.84  16.481  < 2e-16 ***\nremaining_lease_mths        302.83      14.54  20.833  < 2e-16 ***\nPROX_ELDERLYCARE         -31238.50    3124.85  -9.997  < 2e-16 ***\nPROX_HAWKER              -39741.25    4026.06  -9.871  < 2e-16 ***\nPROX_MRT                 -62292.89    5329.61 -11.688  < 2e-16 ***\nPROX_PARK                -28194.94    4719.43  -5.974 2.89e-09 ***\nPROX_GOOD_PRISCH         -10356.76     892.59 -11.603  < 2e-16 ***\nPROX_MALL                 -2453.56    6497.02  -0.378    0.706    \nPROX_CHAS                  4948.91   20109.21   0.246    0.806    \nPROX_SUPERMARKET         -61515.19   14175.78  -4.339 1.52e-05 ***\nWITHIN_350M_KINDERGARTEN  11243.76    2054.96   5.472 5.23e-08 ***\nWITHIN_350M_CHILDCARE     -1963.41    1199.48  -1.637    0.102    \nWITHIN_350M_BUS           -2831.83     715.11  -3.960 7.85e-05 ***\nWITHIN_1KM_PRISCH        -21899.68    1486.35 -14.734  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 75090 on 1484 degrees of freedom\nMultiple R-squared:  0.6021,\tAdjusted R-squared:  0.5981 \nF-statistic: 149.7 on 15 and 1484 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### **Revising the model**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_mlr1 <- lm(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK +\n    PROX_GOOD_PRISCH  + PROX_SUPERMARKET + \n    WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample)\nsummary(HDB_sample_mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + storey_order + remaining_lease_mths + \n    PROX_ELDERLYCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + PROX_GOOD_PRISCH + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + WITHIN_350M_BUS + \n    WITHIN_1KM_PRISCH, data = HDB_sample)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-212902  -43896   -5952   35331  340892 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              168674.79   32366.21   5.211 2.14e-07 ***\nfloor_area_sqm             1978.39     291.07   6.797 1.54e-11 ***\nstorey_order              17508.40    1061.87  16.488  < 2e-16 ***\nremaining_lease_mths        300.22      14.15  21.222  < 2e-16 ***\nPROX_ELDERLYCARE         -30952.98    3100.87  -9.982  < 2e-16 ***\nPROX_HAWKER              -39783.01    3943.94 -10.087  < 2e-16 ***\nPROX_MRT                 -61656.34    5260.21 -11.721  < 2e-16 ***\nPROX_PARK                -28400.02    4691.49  -6.054 1.79e-09 ***\nPROX_GOOD_PRISCH         -10295.45     882.50 -11.666  < 2e-16 ***\nPROX_SUPERMARKET         -57030.62   12922.92  -4.413 1.09e-05 ***\nWITHIN_350M_KINDERGARTEN  10525.61    2009.44   5.238 1.86e-07 ***\nWITHIN_350M_BUS           -3031.21     684.96  -4.425 1.03e-05 ***\nWITHIN_1KM_PRISCH        -22311.90    1404.39 -15.887  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 75090 on 1487 degrees of freedom\nMultiple R-squared:  0.6013,\tAdjusted R-squared:  0.5981 \nF-statistic: 186.9 on 12 and 1487 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### **Multi Linear Regression Model Analysis**\n\n✔️ **p \\< 0.05 (** or *)*\\*\n\nModerate evidence the variable is significant.\n\nIndependent variables are statistically significant like floor_area_sqm, storey_order, remaining_lease_mths, prox_elderlycare, prox_hawker, prox_mrt, prox_park, prox_good_prisch, prox_mall, prox_chas, prox_supermarket, within_350m_kindergarten, within_350m_bus, within_1km_prisch\n\n❌ **p \\> 0.05 (no stars)**\n\nThe variable is not statistically significant like prox_mall, prox_chas and within_350m_childcare →\\\nIt does not have meaningful explanation in this model.\n\n**Adjusted R²**\\\nAdjusted R² tells how much of the variation in resale price is explained by the model after penalizing for the number of variables.\n\n### **Interpretation:**\n\nThe model explains \\~59.8% of the variation in HDB resale prices.\n\nThis is moderately strong for housing data.\n\nIt means that structural and locational factors together account for about 60% of price differences, while the remaining 40% may due to:\n\n-   unobserved buyer preferences,\n\n-   unit condition,\n\n-   renovation works,\n\n-   noise or congestion levels,\n\n-   location-specific externalities not included in the model.\n\n### **Preparing Publication Quality Table: gtsummary method**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(HDB_sample_mlr1, intercept = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bxlyleukkm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bxlyleukkm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bxlyleukkm thead, #bxlyleukkm tbody, #bxlyleukkm tfoot, #bxlyleukkm tr, #bxlyleukkm td, #bxlyleukkm th {\n  border-style: none;\n}\n\n#bxlyleukkm p {\n  margin: 0;\n  padding: 0;\n}\n\n#bxlyleukkm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bxlyleukkm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bxlyleukkm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bxlyleukkm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bxlyleukkm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bxlyleukkm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bxlyleukkm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bxlyleukkm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bxlyleukkm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bxlyleukkm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bxlyleukkm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bxlyleukkm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bxlyleukkm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bxlyleukkm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bxlyleukkm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bxlyleukkm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bxlyleukkm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bxlyleukkm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bxlyleukkm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bxlyleukkm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bxlyleukkm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bxlyleukkm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bxlyleukkm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bxlyleukkm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bxlyleukkm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bxlyleukkm .gt_left {\n  text-align: left;\n}\n\n#bxlyleukkm .gt_center {\n  text-align: center;\n}\n\n#bxlyleukkm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bxlyleukkm .gt_font_normal {\n  font-weight: normal;\n}\n\n#bxlyleukkm .gt_font_bold {\n  font-weight: bold;\n}\n\n#bxlyleukkm .gt_font_italic {\n  font-style: italic;\n}\n\n#bxlyleukkm .gt_super {\n  font-size: 65%;\n}\n\n#bxlyleukkm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bxlyleukkm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bxlyleukkm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bxlyleukkm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bxlyleukkm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bxlyleukkm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bxlyleukkm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bxlyleukkm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bxlyleukkm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">168,675</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">105,187, 232,163</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">floor_area_sqm</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1,978</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1,407, 2,549</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">storey_order</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">17,508</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">15,425, 19,591</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">remaining_lease_mths</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">300</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">272, 328</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-30,953</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-37,036, -24,870</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_HAWKER</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-39,783</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-47,519, -32,047</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-61,656</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-71,975, -51,338</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-28,400</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-37,603, -19,197</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_GOOD_PRISCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-10,295</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-12,027, -8,564</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SUPERMARKET</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-57,031</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-82,380, -31,682</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_350M_KINDERGARTEN</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">10,526</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">6,584, 14,467</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_350M_BUS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-3,031</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-4,375, -1,688</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_1KM_PRISCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-22,312</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-25,067, -19,557</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(HDB_sample_mlr1, \n               intercept = TRUE) %>% \n  add_glance_source_note(\n    label = list(sigma ~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, \n                AIC, statistic,\n                p.value, sigma))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hizxknrruy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hizxknrruy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hizxknrruy thead, #hizxknrruy tbody, #hizxknrruy tfoot, #hizxknrruy tr, #hizxknrruy td, #hizxknrruy th {\n  border-style: none;\n}\n\n#hizxknrruy p {\n  margin: 0;\n  padding: 0;\n}\n\n#hizxknrruy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hizxknrruy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hizxknrruy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hizxknrruy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hizxknrruy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hizxknrruy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hizxknrruy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hizxknrruy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hizxknrruy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hizxknrruy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hizxknrruy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hizxknrruy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hizxknrruy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hizxknrruy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hizxknrruy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hizxknrruy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hizxknrruy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hizxknrruy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hizxknrruy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hizxknrruy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hizxknrruy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hizxknrruy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hizxknrruy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hizxknrruy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hizxknrruy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hizxknrruy .gt_left {\n  text-align: left;\n}\n\n#hizxknrruy .gt_center {\n  text-align: center;\n}\n\n#hizxknrruy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hizxknrruy .gt_font_normal {\n  font-weight: normal;\n}\n\n#hizxknrruy .gt_font_bold {\n  font-weight: bold;\n}\n\n#hizxknrruy .gt_font_italic {\n  font-style: italic;\n}\n\n#hizxknrruy .gt_super {\n  font-size: 65%;\n}\n\n#hizxknrruy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hizxknrruy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hizxknrruy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hizxknrruy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hizxknrruy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hizxknrruy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hizxknrruy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hizxknrruy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hizxknrruy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">168,675</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">105,187, 232,163</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">floor_area_sqm</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1,978</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1,407, 2,549</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">storey_order</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">17,508</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">15,425, 19,591</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">remaining_lease_mths</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">300</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">272, 328</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-30,953</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-37,036, -24,870</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_HAWKER</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-39,783</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-47,519, -32,047</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-61,656</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-71,975, -51,338</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-28,400</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-37,603, -19,197</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_GOOD_PRISCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-10,295</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-12,027, -8,564</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SUPERMARKET</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-57,031</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-82,380, -31,682</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_350M_KINDERGARTEN</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">10,526</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">6,584, 14,467</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_350M_BUS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-3,031</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-4,375, -1,688</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">WITHIN_1KM_PRISCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-22,312</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-25,067, -19,557</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"UsKyID0gMC42MDE7IEFkanVzdGVkIFLCsiA9IDAuNTk4OyBBSUMgPSAzNyw5NTE7IFN0YXRpc3RpYyA9IDE4NzsgcC12YWx1ZSA9IDwwLjAwMTsgz4MgPSA3NSwwOTE=\"><span class='gt_from_md'>R² = 0.601; Adjusted R² = 0.598; AIC = 37,951; Statistic = 187; p-value = &lt;0.001; σ = 75,091</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### **Regression Diagnostics**\n\n#### Multicollinearity test\n\nMulticollinearity occurs when independent variables are not truly independent, meaning a change in one is associated with a change in another. This makes it hard for the model to isolate each variable’s influence on the outcome.\n\nPerforming a multicollinearity test is crucial in multiple linear regression because it ensures the reliability and interpretability of the model’s results. High multicollinearity, where independent variables are highly correlated, inflates the variance of the estimated coefficients, making them unstable, unreliable, and difficult to interpret. This instability can lead to misleading statistical conclusions, such as a variable appearing statistically insignificant when it is not.\n\nIn the code chunk below, the [check_collinearity()](https://easystats.github.io/performance/reference/check_collinearity.html) of performance package is used to test if there are sign of multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(HDB_sample_mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n                     Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n           floor_area_sqm 1.13 [1.08, 1.21]     1.06      0.89     [0.83, 0.93]\n             storey_order 1.16 [1.10, 1.24]     1.08      0.87     [0.81, 0.91]\n     remaining_lease_mths 1.26 [1.20, 1.35]     1.12      0.79     [0.74, 0.84]\n         PROX_ELDERLYCARE 1.07 [1.03, 1.16]     1.04      0.93     [0.86, 0.97]\n              PROX_HAWKER 1.12 [1.08, 1.21]     1.06      0.89     [0.83, 0.93]\n                 PROX_MRT 1.13 [1.08, 1.21]     1.06      0.89     [0.83, 0.93]\n                PROX_PARK 1.19 [1.13, 1.27]     1.09      0.84     [0.79, 0.88]\n         PROX_GOOD_PRISCH 1.28 [1.21, 1.36]     1.13      0.78     [0.73, 0.83]\n         PROX_SUPERMARKET 1.12 [1.07, 1.20]     1.06      0.89     [0.83, 0.94]\n WITHIN_350M_KINDERGARTEN 1.06 [1.03, 1.15]     1.03      0.94     [0.87, 0.97]\n          WITHIN_350M_BUS 1.07 [1.03, 1.16]     1.04      0.93     [0.86, 0.97]\n        WITHIN_1KM_PRISCH 1.21 [1.15, 1.29]     1.10      0.83     [0.77, 0.87]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.vif <- check_collinearity(HDB_sample_mlr1)\nplot(mlr.vif)\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nSince the VIF of the independent variables are less than 10. We can safely conclude that there are no sign of multicollinearity among the independent variables.\n\n#### Test for Non-Linearity\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(HDB_sample_mlr1,\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nThe figure above reveals that most of the data poitns are scattered around the 0 line, hence we can safely conclude that the relationships between the dependent variable and independent variables are linear.\n\n#### Test for Normality Assumption\n\nThe normality assumption test for multiple linear regression checks if the model’s residuals (the differences between observed and predicted values) are normally distributed. This is crucial for accurate hypothesis testing and confidence intervals. To test this, you can use visual methods like histograms and Q-Q plots of the residuals, or conduct statistical tests like Shapiro-Wilk test and Kolmogorov-Smirnov test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(HDB_sample_mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n\nThe print above reveals that the p-value of the normality assumption test is less than alpha value of 0.05. Hence we reject the normality assumption at 95% confident level.\\\n\nInstead of showing the test statistic, `plot()` of **see** package can be used to plot a the output of `check_normality()` for visual inspection as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(HDB_sample_mlr1), \n     type = \"qq\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nFrom the Q-Q plot, the points on the far right curve above the line and This means the model produces large positive residuals for some observations.\n\nInterpretation,\n\nThere are flats where the model underpredicts price and possibly high-end flats or outliers(rare higher price flats)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(HDB_sample_mlr1,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nThe figure reveals that the residual of the multiple linear regression model is resemble normal distribution.\n\n#### Testing for Spatial Autocorrelation\n\nBecause a hedonic pricing model is built using geographically referenced data, it is essential to assess spatial autocorrelation before interpreting the results. Traditional regression techniques, such as ordinary least squares (OLS), assume that observations are independent of one another. Spatial data frequently violates this assumption because nearby locations tend to share similar characteristics.\n\nSpatial autocorrelation refers to the degree to which a variable is correlated with itself across space.\n\nPositive spatial autocorrelation occurs when nearby locations exhibit similar values.\n\nNegative spatial autocorrelation occurs when nearby values are dissimilar.\n\nFailing to account for spatial autocorrelation in a regression model can result in several serious issues:\n\nBiased and inefficient coefficient estimates: When autocorrelation exists, standard errors become unreliable, which affects hypothesis testing and inflates the apparent significance of variables.\n\nMisleading p-values: OLS cannot distinguish true variable effects from underlying spatial patterns, causing inaccurate inference.\n\nModel misspecification: Significant spatial autocorrelation in the residuals suggests that key spatial processes or variables have been omitted. Spatially patterned residuals often reveal where the model is under- or over-predicting.\n\nHigher Type I error rates: Researchers may incorrectly conclude that a variable is significant when it is not.\n\nTo formally assess this, a Moran’s I test can be applied to the regression residuals. A statistically significant Moran’s I indicates that the model has not fully captured the underlying spatial structure.\n\nBefore conducting the test, the residuals from the hedonic model must be extracted and saved as a separate spatial data frame, ensuring they retain their geographic coordinates for spatial autocorrelation analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.output <- as.data.frame(HDB_sample_mlr1$residuals)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_1 <- cbind(HDB_sample, \n                    HDB_sample_mlr1$residuals) %>%\nrename(`MLR_RES` = `HDB_sample_mlr1.residuals`)\n```\n:::\n\n\nuse **tmap** package to display the distribution of the residuals on an interactive map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.4) +\ntm_shape(HDB_sample_1) +  \n  tm_dots(\n    fill = \"MLR_RES\",\n    size = 0.7,\n    col = \"black\",\n    fill.scale = tm_scale(\n      n = 10,\n      values = rev(\n        brewer.pal(11, \"RdBu\")),\n      style = \"quantile\",\n      midpoint = NA),\n    fill.legend = tm_legend(title = \"Residuals\")\n  ) + \n  tm_title(\"LM Residuals (Quantile Classification)\") +\n  tm_layout(legend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_ELDERLYCARE\"         \"PROX_HAWKER\"             \n [7] \"PROX_MRT\"                 \"PROX_PARK\"               \n [9] \"PROX_GOOD_PRISCH\"         \"PROX_MALL\"               \n[11] \"PROX_CHAS\"                \"PROX_SUPERMARKET\"        \n[13] \"WITHIN_350M_KINDERGARTEN\" \"WITHIN_350M_CHILDCARE\"   \n[15] \"WITHIN_350M_BUS\"          \"WITHIN_1KM_PRISCH\"       \n[17] \"LOG_resale_price\"         \"MLR_RES\"                 \n[19] \"geometry\"                \n```\n\n\n:::\n:::\n\n\ncompute the distance-based weight matrix by using [`st_dist_band()`](https://sfdep.josiahparry.com/reference/st_dist_band) function of **sfdep**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_2 <- HDB_sample_1 %>%\n  mutate(\n    nb = st_dist_band(\n      st_geometry(geometry), \n                 upper = 2000),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1) \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(\n  HDB_sample_2$MLR_RES, \n  nb = HDB_sample_2$nb, \n  wt = HDB_sample_2$wt,\n  alternative = \"two.sided\", \n  nsim = 499)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 500 \n\nstatistic = 0.40952, observed rank = 500, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nMoran’s I statistic = 0.40952\n\nThis value measures spatial autocorrelation in your regression residuals.\n\nInterpret the magnitude:\n\n0.41 is high for residuals\n\nTypical Moran’s I values range from -1 to +1\n\n-   0 → random pattern\n\n-   +1 → strong clustering\n\n-   -1 → strong dispersion (checkerboard pattern)\n\nThere is strong positive spatial autocorrelation in the residuals.\\\n\nNearby HDB flats have similar residual values (clusters of overprediction or underprediction).\n\np-value \\< 2.2e-16:\n\nThe spatial autocorrelation is highly statistically significant.\\\n\nThis is not due to random chance.\n\nObserved rank = 500 (highest possible):\n\nOut of all 499 random permutations + 1 observed value\n\nYour observed Moran’s I = largest value\n\nNone of the random simulations came close to your actual autocorrelation\n\nThis strengthens the evidence that the spatial clustering is real and strong.\n\nSince the Observed Global Moran I = 0.14389 which is greater than 0, we can infer than the residuals resemble cluster distribution.\n\n## **Building Hedonic Pricing Models using GWmodel**\n\nModelling hedonic pricing using both the fixed and adaptive bandwidth schemes\n\n### **Building Fixed Bandwidth GWR Model**\n\n#### Computing fixed bandwith\n\nIn the code chunk below, the `bw.gwr()` function from the GWModel package is used to determine the optimal fixed bandwidth for the GWR model. Because the argument `adaptive = FALSE` is specified, the function will compute a fixed (distance-based) bandwidth rather than an adaptive one.\n\nThere are two main methods available for selecting the optimal bandwidth:\n\n1.  Cross-validation (CV)\n\n2.  Corrected Akaike Information Criterion (AICc)\n\nIn this example, the stopping rule for bandwidth selection is determined using the method specified in the `approach` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_fixed <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE  +\n    PROX_MRT + PROX_PARK   +\n    PROX_GOOD_PRISCH  + PROX_SUPERMARKET + PROX_MALL +\n    WITHIN_350M_KINDERGARTEN + PROX_CHAS + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample_2, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=FALSE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed bandwidth: 19127.87 CV score: 8.519883e+12 \nFixed bandwidth: 11824.04 CV score: 7.611516e+12 \nFixed bandwidth: 7310.02 CV score: 5.823607e+12 \nFixed bandwidth: 4520.205 CV score: 4.084202e+12 \nFixed bandwidth: 2796.004 CV score: 3.046563e+12 \nFixed bandwidth: 1730.39 CV score: 2.348023e+12 \nFixed bandwidth: 1071.804 CV score: 2.155032e+12 \nFixed bandwidth: 664.7752 CV score: 2.573514e+12 \nFixed bandwidth: 1323.361 CV score: 2.181079e+12 \nFixed bandwidth: 916.3327 CV score: 2.190123e+12 \nFixed bandwidth: 1167.89 CV score: 2.152987e+12 \nFixed bandwidth: 1227.275 CV score: 2.159522e+12 \nFixed bandwidth: 1131.188 CV score: 2.151907e+12 \nFixed bandwidth: 1108.505 CV score: 2.152397e+12 \nFixed bandwidth: 1145.207 CV score: 2.152046e+12 \nFixed bandwidth: 1122.524 CV score: 2.15199e+12 \nFixed bandwidth: 1136.543 CV score: 2.15192e+12 \nFixed bandwidth: 1127.879 CV score: 2.151923e+12 \nFixed bandwidth: 1133.234 CV score: 2.151906e+12 \nFixed bandwidth: 1134.498 CV score: 2.151909e+12 \nFixed bandwidth: 1132.452 CV score: 2.151905e+12 \nFixed bandwidth: 1131.97 CV score: 2.151905e+12 \nFixed bandwidth: 1132.751 CV score: 2.151905e+12 \nFixed bandwidth: 1132.268 CV score: 2.151905e+12 \nFixed bandwidth: 1132.566 CV score: 2.151905e+12 \nFixed bandwidth: 1132.382 CV score: 2.151905e+12 \nFixed bandwidth: 1132.496 CV score: 2.151905e+12 \nFixed bandwidth: 1132.426 CV score: 2.151905e+12 \nFixed bandwidth: 1132.469 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.436 CV score: 2.151905e+12 \nFixed bandwidth: 1132.446 CV score: 2.151905e+12 \nFixed bandwidth: 1132.44 CV score: 2.151905e+12 \nFixed bandwidth: 1132.444 CV score: 2.151905e+12 \nFixed bandwidth: 1132.441 CV score: 2.151905e+12 \nFixed bandwidth: 1132.443 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \nFixed bandwidth: 1132.442 CV score: 2.151905e+12 \n```\n\n\n:::\n:::\n\n\nThe result shows that the recommended bandwidth is 1132.564\n\n#### GWModel method - fixed bandwith\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE +\n    PROX_MRT + PROX_PARK   +\n    PROX_GOOD_PRISCH  + PROX_SUPERMARKET + PROX_MALL +\n    WITHIN_350M_KINDERGARTEN + PROX_CHAS + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample_2,  \n  bw=bw_fixed, \n  kernel = 'gaussian', \n  longlat = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-16 18:05:16.527186 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_order + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_MRT + PROX_PARK + \n    PROX_GOOD_PRISCH + PROX_SUPERMARKET + PROX_MALL + WITHIN_350M_KINDERGARTEN + \n    PROX_CHAS + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, data = HDB_sample_2, \n    bw = bw_fixed, kernel = \"gaussian\", longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm storey_order remaining_lease_mths PROX_ELDERLYCARE PROX_MRT PROX_PARK PROX_GOOD_PRISCH PROX_SUPERMARKET PROX_MALL WITHIN_350M_KINDERGARTEN PROX_CHAS WITHIN_350M_BUS WITHIN_1KM_PRISCH\n   Number of data points: 1500\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-197183  -46827   -7092   35736  356022 \n\n   Coefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)              198958.16   35197.72   5.653 1.89e-08 ***\n   floor_area_sqm             1577.29     300.11   5.256 1.69e-07 ***\n   storey_order              18415.34    1094.49  16.826  < 2e-16 ***\n   remaining_lease_mths        286.66      14.88  19.270  < 2e-16 ***\n   PROX_ELDERLYCARE         -32427.42    3222.54 -10.063  < 2e-16 ***\n   PROX_MRT                 -63177.91    5493.48 -11.501  < 2e-16 ***\n   PROX_PARK                -34312.67    4835.53  -7.096 1.98e-12 ***\n   PROX_GOOD_PRISCH         -10775.90     920.80 -11.703  < 2e-16 ***\n   PROX_SUPERMARKET         -64683.97   14550.53  -4.445 9.42e-06 ***\n   PROX_MALL                  2606.36    6597.33   0.395  0.69285    \n   WITHIN_350M_KINDERGARTEN   9995.79    2076.41   4.814 1.63e-06 ***\n   PROX_CHAS                -28465.35   20335.22  -1.400  0.16178    \n   WITHIN_350M_BUS           -2321.02     723.99  -3.206  0.00138 ** \n   WITHIN_1KM_PRISCH        -23157.05    1507.48 -15.361  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 77590 on 1486 degrees of freedom\n   Multiple R-squared: 0.5747\n   Adjusted R-squared: 0.571 \n   F-statistic: 154.4 on 13 and 1486 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.945069e+12\n   Sigma(hat): 77274.46\n   AIC:  38050.17\n   AICc:  38050.49\n   BIC:  36739.57\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Fixed bandwidth: 1132.442 \n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                   Min.     1st Qu.      Median     3rd Qu.\n   Intercept                -899210.032 -244013.930  -74007.707   23548.030\n   floor_area_sqm              -695.928    1267.579    1801.300    3256.712\n   storey_order                3108.654    8757.838   10505.818   12544.018\n   remaining_lease_mths         113.874     325.632     393.255     494.935\n   PROX_ELDERLYCARE         -155839.621  -24606.736   -6301.139   12368.179\n   PROX_MRT                 -313668.286  -90523.843  -48858.123  -19367.651\n   PROX_PARK                -265218.816  -31975.369  -12169.843      43.009\n   PROX_GOOD_PRISCH          -79887.731  -16736.277   -6107.395    2670.141\n   PROX_SUPERMARKET         -173999.788  -63946.079   -8189.165   24865.856\n   PROX_MALL                -232837.412  -24475.154    4908.584   59762.733\n   WITHIN_350M_KINDERGARTEN  -15700.486   -5429.653   -1949.314    3415.666\n   PROX_CHAS                -215762.658  -41795.232   -5805.588   41691.848\n   WITHIN_350M_BUS           -11096.036   -1501.346    1266.494    2920.215\n   WITHIN_1KM_PRISCH         -61917.056   -3991.781    1281.154    5250.049\n                                Max.\n   Intercept                527954.1\n   floor_area_sqm             7361.2\n   storey_order              25218.7\n   remaining_lease_mths        715.5\n   PROX_ELDERLYCARE          66743.5\n   PROX_MRT                 212416.3\n   PROX_PARK                118282.2\n   PROX_GOOD_PRISCH          57712.8\n   PROX_SUPERMARKET         208544.5\n   PROX_MALL                143519.4\n   WITHIN_350M_KINDERGARTEN  31474.1\n   PROX_CHAS                302784.0\n   WITHIN_350M_BUS           19222.4\n   WITHIN_1KM_PRISCH         16436.4\n   ************************Diagnostic information*************************\n   Number of data points: 1500 \n   Effective number of parameters (2trace(S) - trace(S'S)): 388.7369 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1111.263 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 35565.27 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 35082.21 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 35561.47 \n   Residual sum of squares: 1.023729e+12 \n   R-square value:  0.9513231 \n   Adjusted R-square value:  0.9342799 \n\n   ***********************************************************************\n   Program stops at: 2025-11-16 18:05:17.085437 \n```\n\n\n:::\n:::\n\n\n#### GWModel Method - Fixed Bandwidth Analysis\n\nAdjusted R-squared (GWR): 0.9343\n\n### Interpretation:\n\nThe GWR model explains 93.4% of the variation in resale prices.\n\nThis is a very large improvement over the global OLS model (Adj R² ≈ 0.571).\n\nThis tells us:\n\n-   Spatial variation is extremely important in explaining HDB prices.\n\n-   The determinants of price vary significantly across space.\n\n-   The global OLS model was missing spatial structure and averaging out effects.\n\n### Interpretation:\n\nAlmost all variables have p \\< 0.001, meaning they are strongly associated with resale prices on average.\n\nHowever, global p-values no longer reflect local significance.\n\nIn GWR:\n\nThe importance of variables changes across space.\n\n### From GWR output:\n\n```         \n   AIC:  38050.17    AICc:  38050    BIC:  36739.57\n```\n\n### Interpretation:\n\nAIC dropped by almost 3,000 points.\n\nThis is an extremely large improvement in model fit.\n\nAICc and BIC also show major reduction → confirms the model is superior even after penalizing complexity.\n\n\\\n\\\n**1. PROX_MRT**\n\n### Very wide coefficient range\n\nLarge negative coefficient→ farther from MRT reduces price strongly\n\nPositive coefficient→ being close from MRT increases price\n\n### Regional variation is expected\n\nSingapore has strong spatial differences in:\n\n-   transport reliance\n\n-   noise tolerance\n\n-   income levels\n\n-   travel patterns\n\n**2. PROX_PARK**\n\n### Large negative → distance from parks reduces value\n\nEspecially near large parks:\n\n-   Bishan–Ang Mo Kio Park\n\n-   East Coast Park\n\n-   West Coast Park\n\n-   Jurong Lake Gardens\n\n-   Bukit Batok Nature Park\n\nThese are major green amenities.\n\n### Positive values occur in areas:\n\n-   where small parks have limited amenity value\n\n-   where parks bring noise (sports courts)\n\n-   lower-end parks or small pocket parks add little value\n\n-   perceived safety concerns in some neighbourhood parks\n\n**3. PROX_GOOD_PRISCH**\n\nNegative coefficients → closer to good school = higher value\n\n-   Strong effect in places like Bukit Timah, Bishan, Marine Parade, Queenstown\n\n-   High competition for school enrollment\n\nPositive coefficients → weaker or adverse school effect\n\nLikely in areas:\n\n-   with oversupply of schools\n\n-   where elite schools are far\n\n-   where accessibility to schools is not a priority for the demographic\n\n**4. PROX_SUPERMARKET**\n\nNegative → far from supermarket reduces value\n\nDaily convenience is critical for many families.\n\nPositive → further is better\n\nThis can happen when:\n\n-   supermarkets bring congestion\n\n-   noise from loading bays\n\n-   smells (wet markets)\n\n-   high-traffic areas around malls\n\n**5. WITHIN_350M_KINDERGARTEN**\n\nPositive coefficients → proximity to childcare highly valued\n\nEspecially in:\n\nyoung towns (Punggol, Sengkang)\n\nfamily-heavy estates\n\nnewer precincts with more young buyers\n\nNegative coefficients → oversupply or negative externalities\n\ntoo many childcare centres = no competitive advantage\n\nnoise during drop-off/pick-up\n\nnot valued by singles or elderly households\n\n### **Building Adaptive Bandwidth GWR Model**\n\nCalibrate the gwr-based hedonic pricing model by using adaptive bandwidth approach\n\n#### Computing the adaptive bandwidth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK   +\n    PROX_GOOD_PRISCH  + PROX_SUPERMARKET + PROX_MALL +\n    WITHIN_350M_KINDERGARTEN  + WITHIN_350M_CHILDCARE+\n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample_2,  \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth: 934 CV score: 7.345954e+12 \nAdaptive bandwidth: 585 CV score: 6.638723e+12 \nAdaptive bandwidth: 368 CV score: 5.716319e+12 \nAdaptive bandwidth: 235 CV score: 4.817613e+12 \nAdaptive bandwidth: 152 CV score: 3.754333e+12 \nAdaptive bandwidth: 101 CV score: 3.057121e+12 \nAdaptive bandwidth: 69 CV score: 2.500718e+12 \nAdaptive bandwidth: 50 CV score: 2.265048e+12 \nAdaptive bandwidth: 37 CV score: 2.07659e+12 \nAdaptive bandwidth: 30 CV score: 1.938054e+12 \nAdaptive bandwidth: 24 CV score: 1.873995e+12 \nAdaptive bandwidth: 22 CV score: 1.871444e+12 \nAdaptive bandwidth: 19 CV score: 1.859432e+12 \nAdaptive bandwidth: 19 CV score: 1.859432e+12 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(HDB_sample_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"nb\"                       \"wt\"                      \n [3] \"resale_price\"             \"floor_area_sqm\"          \n [5] \"storey_order\"             \"remaining_lease_mths\"    \n [7] \"PROX_ELDERLYCARE\"         \"PROX_HAWKER\"             \n [9] \"PROX_MRT\"                 \"PROX_PARK\"               \n[11] \"PROX_GOOD_PRISCH\"         \"PROX_MALL\"               \n[13] \"PROX_CHAS\"                \"PROX_SUPERMARKET\"        \n[15] \"WITHIN_350M_KINDERGARTEN\" \"WITHIN_350M_CHILDCARE\"   \n[17] \"WITHIN_350M_BUS\"          \"WITHIN_1KM_PRISCH\"       \n[19] \"LOG_resale_price\"         \"MLR_RES\"                 \n[21] \"geometry\"                \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm + storey_order  + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK   +\n    PROX_GOOD_PRISCH  + PROX_SUPERMARKET + PROX_MALL +\n    WITHIN_350M_KINDERGARTEN + WITHIN_350M_CHILDCARE +\n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n  data=HDB_sample_2,  \n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-16 18:05:21.966113 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_order + \n    remaining_lease_mths + PROX_ELDERLYCARE + PROX_HAWKER + PROX_MRT + \n    PROX_PARK + PROX_GOOD_PRISCH + PROX_SUPERMARKET + PROX_MALL + \n    WITHIN_350M_KINDERGARTEN + WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + \n    WITHIN_1KM_PRISCH, data = HDB_sample_2, bw = bw.adaptive, \n    kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm storey_order remaining_lease_mths PROX_ELDERLYCARE PROX_HAWKER PROX_MRT PROX_PARK PROX_GOOD_PRISCH PROX_SUPERMARKET PROX_MALL WITHIN_350M_KINDERGARTEN WITHIN_350M_CHILDCARE WITHIN_350M_BUS WITHIN_1KM_PRISCH\n   Number of data points: 1500\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-213809  -43646   -5816   35942  346490 \n\n   Coefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)              175137.98   34314.88   5.104 3.76e-07 ***\n   floor_area_sqm             1960.34     292.29   6.707 2.82e-11 ***\n   storey_order              17545.95    1062.24  16.518  < 2e-16 ***\n   remaining_lease_mths        302.51      14.48  20.898  < 2e-16 ***\n   PROX_ELDERLYCARE         -31177.56    3114.04 -10.012  < 2e-16 ***\n   PROX_HAWKER              -39556.00    3953.82 -10.005  < 2e-16 ***\n   PROX_MRT                 -62200.16    5314.59 -11.704  < 2e-16 ***\n   PROX_PARK                -28143.90    4713.38  -5.971 2.94e-09 ***\n   PROX_GOOD_PRISCH         -10348.16     891.62 -11.606  < 2e-16 ***\n   PROX_SUPERMARKET         -60222.16   13161.99  -4.575 5.15e-06 ***\n   PROX_MALL                 -2587.80    6472.03  -0.400   0.6893    \n   WITHIN_350M_KINDERGARTEN  11243.28    2054.31   5.473 5.19e-08 ***\n   WITHIN_350M_CHILDCARE     -1991.23    1193.76  -1.668   0.0955 .  \n   WITHIN_350M_BUS           -2838.55     714.37  -3.974 7.42e-05 ***\n   WITHIN_1KM_PRISCH        -21902.15    1485.85 -14.741  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 75070 on 1485 degrees of freedom\n   Multiple R-squared: 0.6021\n   Adjusted R-squared: 0.5983 \n   F-statistic: 160.5 on 14 and 1485 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.368925e+12\n   Sigma(hat): 74744.45\n   AIC:  37952.3\n   AICc:  37952.67\n   BIC:  36654.33\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 19 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                   Min.     1st Qu.      Median     3rd Qu.\n   Intercept                -1461502.51  -280584.46   -72395.58    87296.19\n   floor_area_sqm             -15359.15     1100.87     1905.37     3065.08\n   storey_order                 1075.11     8097.08    10492.70    13475.95\n   remaining_lease_mths         -779.78      308.74      403.85      538.37\n   PROX_ELDERLYCARE          -237382.79   -31202.29     -112.08    24470.46\n   PROX_HAWKER               -348704.34   -36777.32    -6455.83    33462.54\n   PROX_MRT                  -527532.25   -91872.48   -54685.29   -21835.89\n   PROX_PARK                 -320212.37   -41248.48   -14448.56    11463.93\n   PROX_GOOD_PRISCH          -629922.19   -21254.39    -7275.81     7814.52\n   PROX_SUPERMARKET          -199784.26   -48454.19    -7886.86    35577.55\n   PROX_MALL                 -236467.45   -31046.32     4177.78    49531.78\n   WITHIN_350M_KINDERGARTEN   -38032.01    -7463.18     -939.10     5026.04\n   WITHIN_350M_CHILDCARE      -14422.00    -2477.60      610.34     2979.40\n   WITHIN_350M_BUS            -13815.72    -2125.10      508.36     2709.40\n   WITHIN_1KM_PRISCH          -57769.06    -5648.51     -388.40     4954.41\n                                  Max.\n   Intercept                3725297.89\n   floor_area_sqm              8482.45\n   storey_order               22981.72\n   remaining_lease_mths         840.69\n   PROX_ELDERLYCARE          258606.43\n   PROX_HAWKER               606013.73\n   PROX_MRT                  183378.47\n   PROX_PARK                 493120.98\n   PROX_GOOD_PRISCH          118635.08\n   PROX_SUPERMARKET          265747.06\n   PROX_MALL                 437349.70\n   WITHIN_350M_KINDERGARTEN   33141.87\n   WITHIN_350M_CHILDCARE      19364.47\n   WITHIN_350M_BUS            12973.72\n   WITHIN_1KM_PRISCH          33750.76\n   ************************Diagnostic information*************************\n   Number of data points: 1500 \n   Effective number of parameters (2trace(S) - trace(S'S)): 603.47 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 896.53 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 35757.03 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 34770.83 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 36391.6 \n   Residual sum of squares: 737361937479 \n   R-square value:  0.9649395 \n   Adjusted R-square value:  0.9413133 \n\n   ***********************************************************************\n   Program stops at: 2025-11-16 18:05:22.931556 \n```\n\n\n:::\n:::\n\n\n#### GWModel Method - Adaptive Bandwidth Analysis\n\nAdjusted R² = 0.9413\n\n\\~94% of the variation in resale prices is explained by the locally varying coefficients.\n\nShows a substantial improvement over:\n\nOLS Adjusted R² ≈ 0.598\n\nGWR fixed Adjusted R² ≈ 0.934\n\nAdaptive GWR fits the data slightly better than fixed GWR due to more flexible neighbourhood structures.\n\n**AIC = 34,770.83**\n\n**AICc = 35,757.03**\n\n**BIC = 36,391.6**\n\n**Interpretation:**\n\nAdaptive GWR outperforms:\n\n-   Global OLS (AIC ≈ 38,052)\n\n-   GWR fixed (AIC ≈ 35,082)\n\nSpatial heterogeneity is strong, and adaptive neighbourhoods capture it better.\n\n**Spatial Weighting & Interpretation**\n\n**Bandwidth = 19 nearest neighbours**\\\n→ Each location uses the nearest 19 observations regardless of physical distance.\n\n-   **Dense towns (e.g., Hougang, Ang Mo Kio):**\\\n    Nearest 19 points are very close → captures fine local variation.\n\n-   **Sparse areas (e.g., Sembawang, Tengah):**\\\n    Nearest 19 points may be further apart → prevents unstable coefficients.\n\n**Result**:\n\nAdaptive GWR produces more stable and regionally appropriate estimates especially in mixed-density cities like Singapore.\n\n**Interpretation of Key Locational Factors (Adaptive GWR)**\n\n**A. PROX_MRT**\n\n➡ Most spatially heterogeneous predictor\n\nNegative areas (up to –527k)\n\nStrong MRT dependence (Yishun, Pasir Ris, Sengkang)\n\nBeing far from MRT produces large price penalties\n\nPositive areas (up to +183k)\n\nBeing closer to MRT lowers value due to:\n\n-   train noise & track vibration\n\n-   crowding at interchange stations\n\n-   undesirable “busy environment”\n\n-   preference for car-centric, quieter neighbourhoods (Bukit Timah, Serangoon Gardens)\n\n**B. PROX_PARK**\n\nNegative coefficients (–320k)\n\n-   Properties far from large parks lose value (e.g., Jurong Lake Gardens, EC Park, Bishan Park)\n\nPositive coefficients (+493k)\n\nIn some regions, being closer to a park is undesirable:\n\n-   noise from playgrounds or sports courts\n\n-   safety concerns at night\n\n-   small, low-value pocket parks\n\n**C. PROX_GOOD_PRISCH**\n\nStrongest negative effect (–629k)\n\n-   Top academic clusters (Bishan, Bukit Timah, Clementi)\n\n-   Parents compete intensely → huge proximity premium\n\nPositive effect (+118k)\n\nAreas where:\n\n-   fewer elite schools → lower valuation impact\n\n-   oversupply of schools reduces differentiation\n\n-   demographic groups (elderly precincts) do not value school access\n\n**D. PROX_SUPERMARKET**\n\nNegative\n\n-   Daily convenience increases value\n\nPositive (+356k)\n\nSupermarkets and malls become disamenities:\n\n-   loading bay noise\n\n-   evening congestion\n\n-   smells from wet markets\n\n-   traffic jams around malls\n\n**E. WITHIN_350M_KINDERGARTEN**\n\nNegative (–38k)\n\nOversupply in some areas → reduced marginal benefit\n\nNoise during peak hours\n\nPositive (+33k)\n\nStrong positive effect in:\n\nPunggol, Sengkang (family-oriented towns)\n\nHDB new-generation estates\n\n### **Stable Structural Predictors**\n\nThese have tight coefficient ranges:\n\n-   **floor_area_sqm**\n\n-   **storey_order**\n\n-   **remaining_lease_mths**\n\n➡ They behave consistently across Singapore → structural rather than locational.\n\n### **Visualising GWR Output**\n\n### **Converting SDF into *sf* data.frame**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample_2_adaptive <- st_as_sf(gwr.adaptive$SDF) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDB_sample_2_adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,500\nColumns: 52\n$ Intercept                   <dbl> -304572.09, -137701.34, -48766.27, -826053…\n$ floor_area_sqm              <dbl> 860.26336, 2150.35362, 1593.94973, 7265.75…\n$ storey_order                <dbl> 5852.124, 14922.992, 15653.546, 17836.652,…\n$ remaining_lease_mths        <dbl> 442.354266, 555.118129, 369.767880, 545.58…\n$ PROX_ELDERLYCARE            <dbl> 185486.540, 3983.770, 8290.318, 36421.057,…\n$ PROX_HAWKER                 <dbl> 47101.316, -64050.878, -9827.720, -44499.4…\n$ PROX_MRT                    <dbl> 8597.140, -4281.050, -33157.784, -15567.52…\n$ PROX_PARK                   <dbl> -25465.244, -21943.311, -13339.709, 35913.…\n$ PROX_GOOD_PRISCH            <dbl> -8016.1559, 4472.5155, -13748.7672, -1310.…\n$ PROX_SUPERMARKET            <dbl> -63200.098, -41063.147, -21331.537, 22741.…\n$ PROX_MALL                   <dbl> 87115.815, -35119.620, -13717.608, -179664…\n$ WITHIN_350M_KINDERGARTEN    <dbl> 5808.8849, 17999.6341, 1498.8934, -17031.8…\n$ WITHIN_350M_CHILDCARE       <dbl> 2443.2789, 3108.8251, -2652.2446, 5529.334…\n$ WITHIN_350M_BUS             <dbl> 3406.89585, -3173.45763, 2298.73955, 1215.…\n$ WITHIN_1KM_PRISCH           <dbl> 31000.602, -10360.791, 6075.289, 7985.656,…\n$ y                           <dbl> 405000, 500888, 385000, 485000, 418000, 28…\n$ yhat                        <dbl> 418164.8, 398225.8, 364366.1, 463318.8, 40…\n$ residual                    <dbl> -13164.8437, 102662.1693, 20633.9253, 2168…\n$ CV_Score                    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Stud_residual               <dbl> -0.64669621, 5.49738879, 0.81766531, 0.916…\n$ Intercept_SE                <dbl> 173758.47, 35559.09, 81764.35, 639709.29, …\n$ floor_area_sqm_SE           <dbl> 1038.3776, 300.0288, 501.5581, 6277.5460, …\n$ storey_order_SE             <dbl> 4129.934, 1424.591, 3305.190, 4395.362, 24…\n$ remaining_lease_mths_SE     <dbl> 72.70684, 17.84292, 45.45623, 380.41461, 2…\n$ PROX_ELDERLYCARE_SE         <dbl> 64761.665, 5673.447, 13025.209, 77776.666,…\n$ PROX_HAWKER_SE              <dbl> 56823.332, 6828.113, 14546.943, 72243.401,…\n$ PROX_MRT_SE                 <dbl> 34615.744, 9596.606, 14997.333, 92731.379,…\n$ PROX_PARK_SE                <dbl> 40892.994, 6532.201, 21005.582, 91542.433,…\n$ PROX_GOOD_PRISCH_SE         <dbl> 27774.473, 2035.456, 7295.514, 32428.004, …\n$ PROX_SUPERMARKET_SE         <dbl> 68740.15, 16455.81, 27736.09, 72100.66, 32…\n$ PROX_MALL_SE                <dbl> 68799.311, 5479.797, 24118.055, 81131.558,…\n$ WITHIN_350M_KINDERGARTEN_SE <dbl> 6471.031, 2716.747, 3326.756, 14373.331, 4…\n$ WITHIN_350M_CHILDCARE_SE    <dbl> 3937.182, 1448.103, 2894.152, 7020.114, 21…\n$ WITHIN_350M_BUS_SE          <dbl> 2783.8951, 908.6762, 1503.4744, 4143.4780,…\n$ WITHIN_1KM_PRISCH_SE        <dbl> 7405.083, 1966.854, 4093.321, 11080.542, 4…\n$ Intercept_TV                <dbl> -1.7528474, -3.8724655, -0.5964246, -1.291…\n$ floor_area_sqm_TV           <dbl> 0.82846870, 7.16715763, 3.17799647, 1.1574…\n$ storey_order_TV             <dbl> 1.4170018, 10.4752794, 4.7360509, 4.058062…\n$ remaining_lease_mths_TV     <dbl> 6.08408073, 31.11139395, 8.13459107, 1.434…\n$ PROX_ELDERLYCARE_TV         <dbl> 2.86414099, 0.70217815, 0.63648256, 0.4682…\n$ PROX_HAWKER_TV              <dbl> 0.82890802, -9.38046505, -0.67558664, -0.6…\n$ PROX_MRT_TV                 <dbl> 0.24835925, -0.44610039, -2.21091207, -0.1…\n$ PROX_PARK_TV                <dbl> -0.6227288, -3.3592525, -0.6350554, 0.3923…\n$ PROX_GOOD_PRISCH_TV         <dbl> -0.28861595, 2.19730349, -1.88455089, -0.0…\n$ PROX_SUPERMARKET_TV         <dbl> -0.91940582, -2.49535789, -0.76908947, 0.3…\n$ PROX_MALL_TV                <dbl> 1.26623092, -6.40892677, -0.56876925, -2.2…\n$ WITHIN_350M_KINDERGARTEN_TV <dbl> 0.89767530, 6.62543674, 0.45055703, -1.184…\n$ WITHIN_350M_CHILDCARE_TV    <dbl> 0.6205654, 2.1468259, -0.9164151, 0.787641…\n$ WITHIN_350M_BUS_TV          <dbl> 1.22378744, -3.49239664, 1.52895155, 0.293…\n$ WITHIN_1KM_PRISCH_TV        <dbl> 4.18639499, -5.26769804, 1.48419586, 0.720…\n$ Local_R2                    <dbl> 0.9115897, 0.8120387, 0.9124804, 0.9276294…\n$ geometry                    <POINT [m]> POINT (39421.92 37093.57), POINT (36…\n```\n\n\n:::\n:::\n\n\n### **Visualising local R2**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDB_sample_2_adaptive) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nThe map visualizes Local R² values from the Adaptive GWR model, showing how well the model explains resale price variation at each specific location across Singapore. Local R² ranges roughly from 0.65 to 1.00, indicating substantial spatial variability in model performance.\n\n\\\n**High Local R² Clusters (0.90 – 1.00)**\n\nThese areas appear as **dark blue points**, concentrated mainly in:\n\n**Central Region**\n\n-   Bishan\n\n-   Toa Payoh\n\n-   Bukit Timah\n\n-   Queenstown\n\n-   Clementi\n\n**Mature Towns (West + East)**\n\n-   Bedok\n\n-   Ang Mo Kio\n\n-   Hougang\n\n-   Jurong East\n\n**Interpretation**\n\nThese are locations where the model captures local price variation extremely well, suggesting:\n\n-   Strong alignment between housing demand and included variables\n\n-   Well-defined neighbourhood characteristics\n\n-   Locational factors (schools, MRT, supermarkets, parks) have **consistent and strong effects**\\\n\nThese towns:\n\n-    have stable, long-established amenities\n\n-   exhibit strong socio-economic patterns (e.g., school demand, transport, green spaces)\n\n-   show consistent structural behaviour (floor area, storey order)\n\n### **Visualising coefficient estimates**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAREA_SQM_SE <- tm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDB_sample_2_adaptive) +\n  tm_dots(\n    fill = \"floor_area_sqm_SE\",       # Use fill= for variable-based colour\n    col = \"gray60\",             # Border colour\n    size = 0.07,\n    lwd = 1\n  )\n\nAREA_SQM_TV <- tm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDB_sample_2_adaptive) +\n  tm_dots(\n    fill = \"floor_area_sqm_TV\",       # Use fill= for variable-based colour\n    col = \"gray60\",             # Border colour\n    size = 0.07,\n    lwd = 1\n  )\n\ntmap_arrange(\n  AREA_SQM_SE,\n  AREA_SQM_TV,\n  asp = 1,\n  ncol = 2,\n  sync = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Assignment_3_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\nLeft Map — floor_area_sqm_SE (Standard Error Map)\n\nThis map visualises the standard error of the local regression coefficient for `floor_area_sqm` across every subzone.\n\nStandard Error (SE) represents the uncertainty or instability of the coefficient estimate in each location.\n\n**Key insight**\n\nMany areas have very low SE, suggesting that the coefficient for floor area is quite stable across most of Singapore.\n\nHigh-SE pockets may indicate neighbourhoods where floor area is less predictive of resale price (e.g., areas dominated by newer apartments, mixed housing types, or gentrifying areas).\n\nRight Map — floor_area_sqm_TV (t-value Map)\n\nThis map visualises the t-value of the coefficient — a measure of statistical significance.\n\n**Key insight**\n\nMost significant signals appear in the central and mature towns, indicating:\n\nIn these places, unit size strongly influences resale price.\n\nFringe regions show weaker significance → price may depend more on location or age than on floor area.\n",
    "supporting": [
      "Assignment_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}