---
title: "In-class_Learning"
author: "HTC"
date: "September 8, 2025"
date-modified: "last-modified"
format:
  html:
    toc-depth: 4
    toc-expand: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

1.1 Overview

This is In-class_Learning,

```{r}
pacman::p_load(sf, raster, spatstat, tidyverse, sparr, tmap)
```

```{r}
pacman::p_load(sf, tidyverse, dplyr, lubridate, httr, tmap,purrr)
```

```{r}
pacman::p_load(sf, tidyverse,httr,tmap)
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Assignment1")
folder_path <- "ACRAInformationonCorporateEntities"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names =TRUE)
acra_data <- file_list %>%
  map_dfr(read_csv)

```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Assignment1")
write_rds(acra_data,
          "data/acra_data.rds")
```

```{r}
biz_56111 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code ==56111) %>%
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         YEAR = year(date),
         MONTH_NUM = month(date),
         MONTH_ABBR = month(date,label = TRUE, abbr = TRUE)) %>%
  mutate(
    postal_code = str_pad(postal_code,
    width = 6, side = "left", pad = "0")) %>% 
          filter(YEAR == 2025)
```

```{r}
postcodes <- unique(biz_56111$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"

found <- data.frame()
not_found <- data.frame(postcode = character())

for (pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "y",
    pageNum = "1")
  res <- GET (url, query = query) 
  json <- content(res)
  if (json$found != 0) {
    df <- as.data.frame(json$results, stringsAsFactors = FALSE) 
    df$input_postcode <- pc 
    found <- bind_rows (found, df)
} else {
not_found <- bind_rows (not_found, data.frame(postcode = pc))
}}
```

```{r}
biz_S6111 = biz_56111 %>% 
  left_join(found,
            by = c('postal_code' = 'POSTAL'))
```

```{r}

```

```{r}
biz_S6111
```

```{r}
```
