---
title: "In-class_Learning_02"
author: "HTC"
date: "September 8, 2025"
date-modified: "last-modified"
format:
  html:
    toc-depth: 4
    toc-expand: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr,GWmodel)
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex04")
hunan_sf <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex04")
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_sf <- left_join(hunan_sf,hunan2012) %>%
  select(1:3, 7, 15,16,31,32)
```

```{r}
hunan_sp <- hunan_sf %>%
  as_Spatial()
```

```{r}
bw_cv <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "AIC",
                adaptive = FALSE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat <- gwss(data = hunan_sp,
                vars = "GDPPC",
                bw = bw_AIC,
                adaptive = FALSE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
gwstat
```

```{r}
gwstat[["SDF"]]
```

```{r}

```

```{r}

```

```{r}

```
