---
title: "In-class_Ex05"
author: "HTC"
date: "September 8, 2025"
date-modified: "last-modified"
format:
  html:
    toc-depth: 4
    toc-expand: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

Overview

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse,spdep)
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex04")
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex")
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/In-Class_Ex")
hunan_GDPPC <- read_csv("data/aspatial/Hunan_GDPPC.csv")
```

```{r}
hunan_2012 <- left_join(hunan, hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
hunan_GDPPC <- left_join(hunan_2012,hunan_GDPPC)
```

```{r}
wm_q <- hunan_GDPPC %>%
  mutate(nb =st_contiguity(geometry),
         wt = st_weights(nb,
                         style ="W"),
         .before =1)
```

```{r}
global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                  nsim=99)
```
