---
title: "Hands-on_Ex03"
author: "HTC"
date: "September 8, 2025"
date-modified: "last-modified"
format:
  html:
    toc-depth: 4
    toc-expand: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 6.1 Overview

This is hands-on Exercise 3 , 6.1

## Getting started

```{r}
pacman::p_load(sf, raster, spatstat, tidyverse, sparr, tmap)
```

```{r}

```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex03")
kbb_sf <- st_read(dsn="data/rawdata",
               layer = "Kepulauan_Bangka_Belitung") %>%
  st_union() %>%
  st_zm(drop = TRUE, what = "ZM") %>%
  st_transform(crs = 32748)
```

```{r}
kbb_owin <- as.owin(kbb_sf)
kbb_owin
```

```{r}
class(kbb_owin)
```

```{r}
plot(kbb_owin)
```

```{r}
setwd("C:/Users/HT Chen/Desktop/ISSS626/ISSS626-wp/Hands-on_Ex/Hands-on_Ex03")
fire_sf <- read_csv("data/rawdata/forestfires.csv") %>%
  st_as_sf(coords = c("longitude", "latitude"),
                       crs = 4326) %>%
  st_transform(crs = 32748)
```

```{r}
fire_sf <- fire_sf %>% 
  mutate(DayofYear = yday(acq_date)) %>%
  mutate(Month_num = month(acq_date)) %>%
  mutate(Month_fac = month(acq_date, 
                           label = TRUE, 
                           abbr = FALSE))
```

```{r}
#DIY
```

```{r}
tm_shape(kbb_sf)+
  tm_polygons() +
tm_shape(fire_sf) +
  tm_dots()
```

```{r}
#DIY2(More edit on catography eg. display each month fire dots)
```

```{r}
tm_shape(kbb_sf)+
  tm_polygons() +
tm_shape(fire_sf) +
  tm_dots(size=0.1) +
tm_facets(by="Month_fac",
          free.coords=FALSE,
          drop.units = TRUE)
```

```{r}
fire_month <- fire_sf %>% 
  select(Month_num)

```

```{r}
fire_month_ppp <- as.ppp(fire_month)
fire_month_ppp
```

`{r}`

```{r}
summary(fire_month_ppp)
```

```{r}
any(duplicated(fire_month_ppp))
```

```{r}
fire_month_owin <- fire_month_ppp[kbb_owin]
summary(fire_month_owin)
```

```{r}
plot(fire_month_owin)
```

```{r}
st_kde <- spattemp.density(fire_month_owin)
summary(st_kde)
```

```{r}
tims <- c(7,8,9,10,11,12)
par(mfcol=c(2,3))
for(i in tims){ 
  plot(st_kde, i, 
       override.par=FALSE, 
       fix.range=TRUE, 
       main=paste("KDE at month",i))
}
```

```{r}
fire_yday_ppp <- fire_sf %>% 
  select(DayofYear) %>%
  as.ppp()
```

```{r}
fire_yday_owin <- fire_yday_ppp[kbb_owin]
summary(fire_yday_owin)
```

```{r}
kde_yday <- spattemp.density(
  fire_yday_owin)
summary(kde_yday)
```

```{r}
plot(kde_yday)
```

```{r}
set.seed(1234)
BOOT.spattemp(fire_yday_owin) 
```

```{r}
kde_yday <- spattemp.density(fire_yday_owin,
                             h = 9000,
                             lambda = 19)
summary(kde_yday)
```

```{r}
plot(kde_yday)
```

```         
```

```{r}
```
